In [16]:
import pandas as pd
from ECOv002_calval_tables import load_calval_table

In [14]:
scene_filename = "../ECOv002_calval_tables/2025-03-03_ECOSTRESS_calval_C2_merged.csv"

In [19]:
scene_df = pd.read_csv(scene_filename)
scene_df = scene_df[["tower", "orbit", "scene", "tile", "time_UTC"]]
scene_df = scene_df.drop_duplicates()
scene_df = scene_df.dropna()
scene_df["orbit"] = scene_df["orbit"].astype(int)
scene_df["scene"] = scene_df["scene"].astype(int)
scene_df.rename(columns={"tower": "ID"}, inplace=True)
scene_df

/var/folders/hk/35_x93nx79vg1zmd2fy1vcbr0000gq/T/ipykernel_15099/141978117.py:1: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  scene_df = pd.read_csv(scene_filename)

            ID  orbit  scene   tile             time_UTC
0       US-xPU   2922      3  05QKB  2019-01-10 18:14:24
10      PE-QFR   3011     13  18MXA  2019-01-16 11:44:11
15      PE-QFR   3079      9  18MXA  2019-01-20 21:27:38
20      PE-QFR   3125      7  18MXA  2019-01-23 20:29:55
25      US-xLE   3143      8  16SCA  2019-01-24 22:55:56
...        ...    ...    ...    ...                  ...
840030  US-SRG  28970      7  12SWA  2023-08-15 21:50:12
840032  US-Whs  28970      7  12SWA  2023-08-15 21:50:12
840034  US-SRS  28970      7  12SWA  2023-08-15 21:50:12
840036  US-SRM  28970      7  12SWA  2023-08-15 21:50:12
840038  US-CMW  28970      7  12SWA  2023-08-15 21:50:12

[54394 rows x 5 columns]

In [17]:
df = load_calval_table()
df

,Unnamed: 0,ID,vegetation,climate,STICinst,BESSinst,MOD16inst,PTJPLSMinst,ETinst,ETinstUncertainty,...,insitu_LE_Wm2,insitu_H_Wm2,insitu_Rn_Wm2,insitu_G_Wm2,insitu_SWin_Wm2,insitu_Ta_C,insitu_RH,insitu_Rn_daylight_Wm2,insitu_LE_daylight_Wm2,insitu_ET_daylight_kg
0,0,US-NC3,ENF,Cfa,270.345200,78.53355,392.851840,307.021970,487.383423,118.916280,...,331.723100,69.623470,449.65123,14.831077,596.8641,31.80107,0.636848,268.829847,205.089552,3.521847
1,1,US-Mi3,CVM,Dfb,232.141600,229.20093,640.118470,375.089300,106.825577,167.919460,...,276.182074,228.756306,667.81900,38.638200,NaN,26.23260,NaN,346.382557,152.046364,3.361398
2,2,US-Mi3,CVM,Dfb,356.355740,335.23154,625.661700,284.686250,NaN,132.936340,...,336.849808,169.322709,603.26000,26.775450,NaN,30.26300,NaN,311.373843,181.941076,4.018909
3,3,US-Mi3,CVM,Dfb,332.938400,326.68680,624.254330,251.414490,178.827545,141.132420,...,276.264202,231.754374,551.03800,13.319750,NaN,23.63330,NaN,298.014172,153.111127,3.377459
4,4,US-Mi3,CVM,Dfb,286.854030,237.21654,511.082180,228.520170,154.791626,114.809410,...,192.205091,155.974781,512.27100,6.896745,NaN,24.33430,NaN,300.483101,114.280419,2.519399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1060,1060,US-xAE,GRA,Cfa,70.923310,172.37459,81.645230,15.282976,NaN,56.385185,...,9.395804,120.547093,171.34000,-13.347000,354.4450,2.23884,0.507300,130.709188,6.649726,0.094448
1061,1061,US-xAE,GRA,Cfa,116.543190,121.81641,65.469320,22.186659,NaN,40.509410,...,46.867192,219.669478,177.33000,53.722333,392.6050,16.94966,0.386400,189.792524,71.961900,1.284029
1062,1062,US-xAE,GRA,Cfa,129.880100,0.00000,118.777240,55.343586,NaN,52.403820,...,52.590710,113.437738,147.91000,45.282667,385.0550,34.05052,0.079800,151.583691,77.678077,1.461298
1063,1063,US-xAE,GRA,Cfa,2.707851,140.38632,126.490524,40.434025,NaN,57.769722,...,91.493744,345.421536,338.90000,2.386667,552.7300,10.91754,0.326400,291.834038,79.346005,1.500961
1064,1064,US-xAE,GRA,Cfa,303.242950,0.00000,271.749480,119.763630,190.823303,122.092445,...,154.783501,518.549629,631.47000,95.436333,966.0500,29.57192,0.255400,331.951225,95.853257,1.842696

In [18]:
df[["ID", "time_UTC"]]

          ID             time_UTC
0     US-NC3  2019-10-02 19:09:40
1     US-Mi3  2019-06-23 18:17:17
2     US-Mi3  2019-06-27 16:35:42
3     US-Mi3  2019-06-30 15:44:10
4     US-Mi3  2019-07-01 14:53:48
...      ...                  ...
1060  US-xAE  2021-12-11 16:01:12
1061  US-xAE  2022-03-25 22:45:31
1062  US-xAE  2022-04-12 22:53:09
1063  US-xAE  2022-04-14 14:45:37
1064  US-xAE  2022-04-20 19:38:47

[1065 rows x 2 columns]

In [21]:
merged_df = pd.merge(df, scene_df, on=["ID", "time_UTC"], how="left")
merged_df

,Unnamed: 0,ID,vegetation,climate,STICinst,BESSinst,MOD16inst,PTJPLSMinst,ETinst,ETinstUncertainty,...,insitu_G_Wm2,insitu_SWin_Wm2,insitu_Ta_C,insitu_RH,insitu_Rn_daylight_Wm2,insitu_LE_daylight_Wm2,insitu_ET_daylight_kg,orbit,scene,tile
0,0,US-NC3,ENF,Cfa,270.345200,78.53355,392.851840,307.021970,487.383423,118.916280,...,14.831077,596.8641,31.80107,0.636848,268.829847,205.089552,3.521847,7038,5,18SUE
1,1,US-Mi3,CVM,Dfb,232.141600,229.20093,640.118470,375.089300,106.825577,167.919460,...,38.638200,NaN,26.23260,NaN,346.382557,152.046364,3.361398,5470,8,17TNG
2,2,US-Mi3,CVM,Dfb,356.355740,335.23154,625.661700,284.686250,NaN,132.936340,...,26.775450,NaN,30.26300,NaN,311.373843,181.941076,4.018909,5531,7,17TNG
3,3,US-Mi3,CVM,Dfb,332.938400,326.68680,624.254330,251.414490,178.827545,141.132420,...,13.319750,NaN,23.63330,NaN,298.014172,153.111127,3.377459,5577,8,17TNG
4,4,US-Mi3,CVM,Dfb,286.854030,237.21654,511.082180,228.520170,154.791626,114.809410,...,6.896745,NaN,24.33430,NaN,300.483101,114.280419,2.519399,5592,8,17TNG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1060,1060,US-xAE,GRA,Cfa,70.923310,172.37459,81.645230,15.282976,NaN,56.385185,...,-13.347000,354.4450,2.23884,0.507300,130.709188,6.649726,0.094448,19465,4,14SME
1061,1061,US-xAE,GRA,Cfa,116.543190,121.81641,65.469320,22.186659,NaN,40.509410,...,53.722333,392.6050,16.94966,0.386400,189.792524,71.961900,1.284029,21083,5,14SME
1062,1062,US-xAE,GRA,Cfa,129.880100,0.00000,118.777240,55.343586,NaN,52.403820,...,45.282667,385.0550,34.05052,0.079800,151.583691,77.678077,1.461298,21362,13,14SME
1063,1063,US-xAE,GRA,Cfa,2.707851,140.38632,126.490524,40.434025,NaN,57.769722,...,2.386667,552.7300,10.91754,0.326400,291.834038,79.346005,1.500961,21388,7,14SME
1064,1064,US-xAE,GRA,Cfa,303.242950,0.00000,271.749480,119.763630,190.823303,122.092445,...,95.436333,966.0500,29.57192,0.255400,331.951225,95.853257,1.842696,21484,13,14SME